### PR TITLE
Fix circular refrerence false positive

### PR DESCRIPTION
**Pull request by andrew-sayers--frontier-forums**
Hey, this was really useful but I've also been bitten by issue #14.  This patch seems to fix it for me.

### CODE REVIEW

**Comment by epoberezkin** [comment]
This seems to be correct, it doesn't allow real circular reference but it allows using the same object in different properties... Why it's not accepted?

**Comment by seburgi** [comment]
Is there anything left to do, that blocks this PR?

**Comment by epoberezkin** [comment]
I don't know. Maybe the test. I even tweeted @substack, but he's probably got too many other things...

**Comment by revolunet** [comment]
i can confirm this fixes the issue

**Comment by h0ward** [comment]
This fix works for me.

**Comment by epoberezkin** [comment]
One more attempt before switching to fork... :) @substack, any plans to merge this PR?

**Comment by substack** [comment]
Is there a way to reproduce this issue for the test suite?

**Comment by hawkrives** [comment]
I think that #19 adds a test for this.

**Comment by epoberezkin** [comment]
Thank you very much! It resolves my issue (above).

**Pull request closed without merging**
